/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=ProductionEnv server/production-env.d.ts` (hash: dfbf25b419c463eb27113e995e097cc7)
interface __BaseEnv_ProductionEnv {
	DB: D1Database;
	EMAIL: SendEmail;
	SAFETY_QUEUE: Queue;
	AI: Ai;
	ASSETS: Fetcher;
	APP_URL: string;
	ENVIRONMENT: string;
	MAINTENANCE_MODE: string;
	NODE_ENV: string;
	ADMIN_EMAILS: string;
	STRIPE_SEASON_PASS_PRODUCT_ID: string;
	STRIPE_SEASON_PASS_PRICE_ID: string;
	EMAIL_FROM: string;
	EMAIL_FROM_NAME: string;
	EMAIL_DELIVERY_ENABLED: string;
	INDEXNOW_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index-worker");
	}
	interface Env extends __BaseEnv_ProductionEnv {}
}
interface ProductionEnv extends __BaseEnv_ProductionEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_URL" | "ENVIRONMENT" | "MAINTENANCE_MODE" | "NODE_ENV" | "ADMIN_EMAILS" | "STRIPE_SEASON_PASS_PRODUCT_ID" | "STRIPE_SEASON_PASS_PRICE_ID" | "EMAIL_FROM" | "EMAIL_FROM_NAME" | "EMAIL_DELIVERY_ENABLED" | "INDEXNOW_KEY">> {}
}
