/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=ProductionEnv server\production-env.d.ts` (hash: 5449002d284897b13b16f8dd7ad03033)
interface __BaseEnv_ProductionEnv {
	DB: D1Database;
	EMAIL: SendEmail;
	SAFETY_QUEUE: Queue;
	PARENT_AGENT_QUEUE: Queue;
	AI: Ai;
	ASSETS: Fetcher;
	APP_URL: string;
	ENVIRONMENT: string;
	PARENT_WHATSAPP_ENABLED: string;
	PARENT_ASSISTANT_ENABLED: string;
	PARENT_AGENT_SDK_ENABLED: string;
	PARENT_REMINDERS_ENABLED: string;
	FAMILY_CHECKOUT_ENABLED: string;
	PARENT_LAUNCH_VERIFIED: string;
	PARENT_REMINDER_CONTENT_SID: string;
	PARENT_AGENT_QUEUE_NAME: string;
	TWILIO_WHATSAPP_FROM: string;
	MAINTENANCE_MODE: string;
	NODE_ENV: string;
	ADMIN_EMAILS: string;
	STRIPE_SEASON_PASS_PRODUCT_ID: string;
	STRIPE_SEASON_PASS_PRICE_ID: string;
	STRIPE_FAMILY_PREMIUM_PRICE_ID: string;
	EMAIL_FROM: string;
	EMAIL_FROM_NAME: string;
	EMAIL_DELIVERY_ENABLED: string;
	INDEXNOW_KEY: string;
	PARENT_ASSISTANT_AGENT: DurableObjectNamespace<import("./index-worker").ParentAssistantAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index-worker");
		durableNamespaces: "ParentAssistantAgent";
	}
	interface Env extends __BaseEnv_ProductionEnv {}
}
interface ProductionEnv extends __BaseEnv_ProductionEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_URL" | "ENVIRONMENT" | "PARENT_WHATSAPP_ENABLED" | "PARENT_ASSISTANT_ENABLED" | "PARENT_AGENT_SDK_ENABLED" | "PARENT_REMINDERS_ENABLED" | "FAMILY_CHECKOUT_ENABLED" | "PARENT_LAUNCH_VERIFIED" | "PARENT_REMINDER_CONTENT_SID" | "PARENT_AGENT_QUEUE_NAME" | "TWILIO_WHATSAPP_FROM" | "MAINTENANCE_MODE" | "NODE_ENV" | "ADMIN_EMAILS" | "STRIPE_SEASON_PASS_PRODUCT_ID" | "STRIPE_SEASON_PASS_PRICE_ID" | "STRIPE_FAMILY_PREMIUM_PRICE_ID" | "EMAIL_FROM" | "EMAIL_FROM_NAME" | "EMAIL_DELIVERY_ENABLED" | "INDEXNOW_KEY">> {}
}
