/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.d1-account-rehearsal.jsonc --include-runtime=false --strict-vars=false --env-interface=AccountRehearsalEnv scripts/d1/account-rehearsal-env.d.ts` (hash: 3e2343bb452059da918b4666f4ae4820)
interface __BaseEnv_AccountRehearsalEnv {
	DB: D1Database;
	REHEARSAL_DATABASE_ID: string;
	REHEARSAL_EXPIRES_AT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./account-rehearsal-worker");
	}
	interface Env extends __BaseEnv_AccountRehearsalEnv {}
}
interface AccountRehearsalEnv extends __BaseEnv_AccountRehearsalEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REHEARSAL_DATABASE_ID" | "REHEARSAL_EXPIRES_AT">> {}
}
