/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.d1-production-copy.jsonc --include-runtime=false --strict-vars=false --env-interface=ProductionCopyEnv scripts/d1/production-copy-env.d.ts` (hash: 49489e775b2c32322a9e0650c876e6c6)
interface __BaseEnv_ProductionCopyEnv {
	DB: D1Database;
	HYPERDRIVE: Hyperdrive;
	COPY_TARGET_ID: string;
	COPY_EXPIRES_AT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./production-copy-worker");
	}
	interface Env extends __BaseEnv_ProductionCopyEnv {}
}
interface ProductionCopyEnv extends __BaseEnv_ProductionCopyEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "COPY_TARGET_ID" | "COPY_EXPIRES_AT">> {}
}
