import React, { type ReactNode, type CSSProperties } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, Brain, Check, ChevronDown, HeartHandshake, Leaf, Lightbulb, LockKeyhole, Shapes, Sprout, Sun, Timer, type LucideIcon } from 'lucide-react';
import { KINDERLEARNER, KINDERLEARNER_PAGES, KL_FAQS, kinderLearnerStartHref, type KinderLearnerPage } from './kinderlearner';

const powers: {name:string; color:string; icon:LucideIcon; copy:string}[] = [
  {name:'Word Power',color:'#6B6ECF',icon:BookOpen,copy:'Build the foundations of language and reading through sounds, letters, vocabulary, blending and early decoding.'},
  {name:'Number Power',color:'#E3A33B',icon:Shapes,copy:'Develop number sense through counting, quantities, patterns, comparison, number composition and early arithmetic.'},
  {name:'Brain Power',color:'#A36BAC',icon:Brain,copy:'Strengthen working memory, attention, sequencing, flexible thinking and self-control through playful challenges.'},
  {name:'Builder Power',color:'#4F8EB5',icon:Lightbulb,copy:'Develop spatial reasoning, planning, patterns and problem solving through exploration and construction.'},
  {name:'People Power',color:'#D97772',icon:HeartHandshake,copy:'Practice understanding emotions, friendship, communication, perspective and everyday social situations.'},
];

function Icon({icon:IconComponent,...props}:{icon:LucideIcon; className?:string}) { return <IconComponent aria-hidden="true" size={22} strokeWidth={1.7} {...props}/>; }
function Section({id,eyebrow,title,children,tone='',className=''}:{id?:string;eyebrow?:string;title?:string;children:ReactNode;tone?:string;className?:string}) {
  return <section id={id} className={`kl-section ${tone ? `kl-${tone}` : ''} ${className}`}><div className="kl-container">{eyebrow && <p className="kl-eyebrow">{eyebrow}</p>}{title && <h2>{title}</h2>}{children}</div></section>;
}
export function KinderLearnerCTA({label='Start KinderLearner',secondary=false}:{label?:string;secondary?:boolean}) {
  const href = kinderLearnerStartHref();
  const external = href.startsWith('https:');
  return <a className={`kl-button ${secondary ? 'kl-button-light' : ''}`} href={href} {...(external ? {target:'_blank',rel:'nofollow noopener noreferrer'} : {})}>{external ? label : 'iOS & iPadOS · Coming soon'}<ArrowUpRight size={18} aria-hidden="true"/></a>;
}
function Brand(){return <a href="/kinderlearner" className="kl-brand"><span className="kl-brand-mark"><Sprout size={25} aria-hidden="true"/></span><span>KinderLearner<small>from NYC School Ratings</small></span></a>;}

export function ParentCoachCard({variant='number',compact=false}:{variant?:'number'|'sound'|'blend';compact?:boolean}) {
  const content = {
    number:{skill:'Number Composition',body:'Your child can count objects confidently but is still learning that one number can be made from smaller groups.',activity:'Put seven grapes on the table. Move two to one side and ask:',question:'“If these are two, how many are over there?”'},
    sound:{skill:'Beginning Sounds',body:'Your child recognizes several letters but still needs practice listening for the first sound in spoken words.',activity:'At breakfast, say: moon · cat · milk. Ask:',question:'“Which two begin with the same sound?”'},
    blend:{skill:'Sound Blending',body:'Your child recognizes several letter sounds independently but is still learning how to combine those sounds into a complete word.',activity:'Say: /m/ — /a/ — /p/. Ask:',question:'“What word do those sounds make together?”'},
  }[variant];
  if(compact) return <aside className="kl-week-card" aria-label="Illustrative parent insight"><div className="kl-week-top"><span className="kl-icon-chip"><Leaf size={18} aria-hidden="true"/></span><strong>This Week</strong></div><p><span>SHOWING CONFIDENCE</span>Counting to 10</p><p><span>WORKING ON</span>Sound blending</p><div className="kl-tonight"><span>TRY TONIGHT · 3 MIN</span><strong>A little sound game.<br/>A meaningful next step.</strong></div></aside>;
  return <article className="kl-coach-card"><div className="kl-week-top"><span className="kl-icon-chip"><Leaf aria-hidden="true" size={22}/></span><strong>This Week</strong><span className="kl-sample">Example insight</span></div><p className="kl-eyebrow">{variant==='blend'?'Currently learning':'Working on'}</p><h3>{content.skill}</h3><p>{content.body}</p><div className="kl-tonight"><p className="kl-eyebrow">Try this tonight · 3 min</p><p>{content.activity}</p><blockquote>{content.question}</blockquote></div><p className="kl-small">A little practice, woven into real life.</p></article>;
}

function ProductPreview(){return <figure className="kl-preview"><div className="kl-tablet"><div className="kl-tablet-camera"/><div className="kl-device-screen"><div className="kl-device-top"><span><Sun size={18} aria-hidden="true"/> Hi Maya</span><span className="kl-session-dot">A little every day</span></div><h2>Today’s Adventure</h2><p className="kl-small">A little wonder. A new discovery.</p><div className="kl-activity"><span className="kl-eyebrow">Number Power</span><h3>How many ways<br/>can you make 7?</h3><div className="kl-counter-tray" aria-label="Seven objects, grouped into four and three"><span className="kl-object-group">{Array.from({length:4},(_,i)=><i key={i}/>)}</span><span className="kl-object-group kl-object-sage">{Array.from({length:3},(_,i)=><i key={i}/>)}</span></div><div className="kl-number-equation"><span>4</span><span>+</span><span>3</span><span>=</span><strong>7</strong></div></div><div className="kl-device-domains">{powers.slice(0,3).map(p=><span key={p.name} style={{'--domain':p.color} as CSSProperties}><Icon icon={p.icon}/>{p.name}</span>)}</div><div className="kl-device-bottom"><span>Explore at your own pace</span><span><Check size={14} aria-hidden="true"/> Grown-up nearby</span></div></div></div><ParentCoachCard compact/><figcaption>Illustrative product preview · Child play + parent insight</figcaption></figure>;}

export function KinderLearnerHero({page}:{page:KinderLearnerPage}){
  const meta=KINDERLEARNER_PAGES[page];
  return <section className={`kl-hero ${page!=='home'?'kl-age-hero':''}`}><div className="kl-container kl-hero-grid"><div className="kl-hero-copy"><p className="kl-eyebrow"><span className="kl-live-dot"/> KinderLearner · {meta.ages}</p><h1>{meta.heading}</h1>{page==='home'?<p className="kl-lead">KinderLearner is a personalized learning adventure that adapts to your child across reading, math, memory, reasoning and social skills — then gives you simple ways to keep the learning going at home.</p>:<><p className="kl-subheading">{page==='prek'?'Playful learning that adapts to your child.':'Reading. Math. Memory. Reasoning. Confidence.'}</p><p className="kl-lead">{page==='prek'?'Pre-K is about much more than memorizing letters and numbers. Children are beginning to understand sounds, quantities, patterns, emotions, sequences, rules and how the world fits together.':'Kindergarten is when many early skills begin connecting. Letters become sounds. Sounds become words. Counting becomes number sense. Objects become equations.'}</p><p>{page==='prek'?'KinderLearner turns those early skills into short, playful learning adventures — and adjusts what comes next based on what your child demonstrates.':'Children are also learning how to focus, remember instructions, solve problems and work independently. KinderLearner strengthens those skills through short, personalized learning adventures.'}</p></>}
    <div className="kl-actions"><KinderLearnerCTA label={page==='home'?'Start KinderLearner':page==='prek'?'Start Pre-K Learning':'Start Kindergarten Practice'}/><a className="kl-text-link" href="#how-it-works">See How It Works <ArrowRight size={18} aria-hidden="true"/></a></div><p className="kl-trust"><LockKeyhole size={14} aria-hidden="true"/> Private <span>·</span> Ad-free <span>·</span> Parent-guided</p><p className="kl-roadmap-note">Product preview, including planned activities. <a href="/kinderlearner/support#current-build">See what’s in the current build.</a></p></div><ProductPreview/></div><div className="kl-container kl-hero-note"><span>For them: <strong>Play. Discover. Grow.</strong></span><span>For you: <strong>A clearer picture. A useful next step.</strong></span></div></section>;
}

function LearningLoop(){return <ol className="kl-loop">{[['01','Play & discover','Your child explores a playful challenge.'],['02','Notice & understand','We notice what comes easily and where help is useful.'],['03','Choose what’s next','An evolving learning profile guides the next activity.'],['04','Take it into real life','You get a simple idea to try together.'],['05','Come back & remember','Skills return later to see what has stuck.']].map(([n,title,body])=><li key={n}><span className="kl-step-number">{n}</span><h3>{title}</h3><p>{body}</p></li>)}</ol>;}
export function AdaptiveLearningFlow({steps=['Count objects','Understand quantity','Match quantity to numeral','Break numbers apart','Early addition']}:{steps?:string[]}){return <ol className="kl-progression">{steps.map((step,i)=><li key={step}><span>{String(i+1).padStart(2,'0')}</span><strong>{step}</strong>{i<steps.length-1&&<ArrowRight aria-hidden="true" size={18}/>}</li>)}</ol>;}
export function LearningPowerCard({power}:{power:typeof powers[number]}){return <article className="kl-power-card" style={{'--domain':power.color} as CSSProperties}><span className="kl-domain-icon"><Icon icon={power.icon}/></span><h3>{power.name}</h3><p>{power.copy}</p></article>;}
export function MasteryEvidenceCard(){return <article className="kl-evidence"><p className="kl-eyebrow">A fuller picture of progress</p><h3>Number Composition</h3><ul>{['Solved with objects','Solved with pictures','Completed independently','Remembered 3 days later'].map(s=><li key={s}><Check size={18} aria-hidden="true"/>{s}</li>)}</ul><div className="kl-evidence-status"><span className="kl-ring"><Sprout size={24} aria-hidden="true"/></span><span><strong>Getting Stronger</strong><small>Confidence across different moments</small></span></div><span className="kl-sample">Illustrative learning evidence, not a test score</span></article>;}
export function RealWorldMissionCard({title,body,icon=Shapes,color='#E3A33B'}:{title:string;body:string;icon?:LucideIcon;color?:string}){return <article className="kl-mission" style={{'--domain':color} as CSSProperties}><span className="kl-domain-icon"><Icon icon={icon}/></span><p className="kl-eyebrow">Off-screen discovery</p><h3>{title}</h3><p>{body}</p><span className="kl-mission-bottom"><HeartHandshake size={17} aria-hidden="true"/> Better together</span></article>;}
function Missions({page}:{page:KinderLearnerPage}){return <Section eyebrow="Real World Missions" title={page==='home'?'The learning doesn’t stop when the iPad closes':page==='prek'?'From screen learning to real-world play':'Small missions. Real-world understanding.'} tone="sand"><p className="kl-intro">Young children learn by moving, touching, talking and experimenting. Everyday objects and conversations become learning opportunities.</p><div className="kl-grid kl-grid-three"><RealWorldMissionCard title="Number Mission" body={page==='kindergarten'?'Get seven small objects. Move three away. How many remain?':'Find 7 objects. Make one group of 4. How many belong in the other group?'}/><RealWorldMissionCard title={page==='kindergarten'?'Reading Mission':'Sound Mission'} body={page==='kindergarten'?'Find two objects around the room that begin with the same sound.':'Find three things around the room that begin with the /b/ sound.'} icon={BookOpen} color="#6B6ECF"/><RealWorldMissionCard title={page==='prek'?'Memory Mission':'Brain Mission'} body={page==='kindergarten'?'Ask a grown-up to give you three simple instructions. Can you remember them in order?':'Ask a grown-up to clap a short pattern. Can you repeat it?'} icon={Brain} color="#A36BAC"/></div><p className="kl-section-close">{page==='prek'?'KinderLearner provides the challenge. Your home becomes part of the learning experience.':'The iPad starts the activity. You and your child finish it together.'}</p></Section>;}
function Coach({page}:{page:KinderLearnerPage}){return <Section className="kl-coach-section"><div className="kl-split"><div><p className="kl-eyebrow">A thoughtful partner for parents</p><h2>{page==='home'?'A learning app for parents, too':page==='prek'?'Simple guidance for parents':'Useful insight for parents'}</h2><p className="kl-lead">Parents don’t need another dashboard filled with percentages.</p><p>KinderLearner explains what your child is learning and gives you simple ways to reinforce it in everyday life.</p><p className="kl-statement">No worksheets.<br/>No lesson planning.<br/><strong>Just a useful activity at the right time.</strong></p><KinderLearnerCTA/></div><ParentCoachCard variant={page==='prek'?'sound':page==='kindergarten'?'blend':'number'}/></div></Section>;}
export function ShortSessionTimeline(){return <ol className="kl-session-timeline">{[['Warm up','A quick skill your child already knows'],['Explore','Something they’re currently learning'],['Think','A playful thinking challenge'],['Remember','A memory or reasoning game'],['Take it outside','An optional Real World Mission']].map(([title,body],i)=><li key={title}><span>{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol>;}
export function PrivacyFeature({children}:{children:ReactNode}){return <li><Check size={18} aria-hidden="true"/>{children}</li>;}
function Privacy(){return <Section eyebrow="A calmer kind of technology" title="Private by design" tone="sage"><div className="kl-privacy-layout"><div><span className="kl-privacy-icon"><LockKeyhole size={32} aria-hidden="true"/></span><p className="kl-lead">Children deserve technology designed differently.</p><p>KinderLearner is built around a privacy-first philosophy.</p><p className="kl-statement">The product has one purpose:<br/><strong>helping children learn.</strong></p></div><ul className="kl-privacy-list">{['No advertising','No public profiles','No child-to-child messaging','No competitive leaderboards','No pressure-based streaks','No attention-maximizing social feed'].map(s=><PrivacyFeature key={s}>{s}</PrivacyFeature>)}</ul></div></Section>;}
export function AgePathCard({page}:{page:'prek'|'kindergarten'}){const prek=page==='prek';return <a className="kl-age-card" href={KINDERLEARNER_PAGES[page].path}><span className="kl-eyebrow">{prek?'The foundations':'The next connections'} · {KINDERLEARNER_PAGES[page].ages}</span><h3>{prek?'Pre-K':'Kindergarten'}</h3><p>{prek?'Sounds, letters, counting, quantities, patterns, memory, emotions and problem solving.':'Phonics, sound blending, number sense, early arithmetic, memory, reasoning and independence.'}</p><span className="kl-text-link">Explore {prek?'Pre-K':'Kindergarten'} Learning <ArrowRight size={18} aria-hidden="true"/></span></a>;}
export function KinderLearnerFAQ({page}:{page:KinderLearnerPage}){return <Section title="A few things parents ask" className="kl-faq-section"><div className="kl-faq">{KL_FAQS[page].map(faq=><details key={faq.question}><summary>{faq.question}<ChevronDown size={20} aria-hidden="true"/></summary><p>{faq.answer}</p></details>)}</div></Section>;}
function Closing({page}:{page:KinderLearnerPage}){return <Section tone="green" className="kl-closing"><p className="kl-eyebrow">Personalized learning. Practical guidance.</p><h2>{page==='home'?<>For the child, it’s an adventure.<br/>For the parent, it’s insight.</>:page==='prek'?'Prepare for Kindergarten without turning home into school':'One child’s Kindergarten journey shouldn’t look exactly like another’s'}</h2><p className="kl-intro">{page==='home'?'KinderLearner gives children playful challenges they want to complete. Behind the scenes, it builds a clearer picture of how they are learning — then turns that insight into something you can actually use.':page==='prek'?'School readiness isn’t about racing ahead. It’s about building strong foundations in language, number sense, memory, attention, reasoning, curiosity and confidence.':'KinderLearner follows the skills beneath broad categories like Reading and Math. As your child grows, their learning path grows with them.'}</p><p className="kl-closing-promise">{page==='kindergarten'?'Practice what matters. Build confidence. Know what to work on next.':'Know how your child is learning. Know what to do next.'}</p><KinderLearnerCTA secondary label={page==='prek'?'Start KinderLearner for Pre-K':'Start KinderLearner'}/><p className="kl-trust">Ages 3–6 · Private · Ad-free · Parent-guided</p></Section>;}

function HomeStory(){return <>
  <Section id="how-it-works" eyebrow="Play with purpose" title="More than another educational game"><div className="kl-split"><div><p className="kl-lead">Most learning apps focus on whether a child got an answer right or wrong.</p><p><strong>KinderLearner looks deeper.</strong></p><p>As your child plays, it builds an evolving picture of what they understand confidently, where they still need support, how independently they solve problems, and what they are ready to learn next.</p><p className="kl-statement">The goal isn’t more screen time.<br/><strong>It’s better learning.</strong></p></div><div className="kl-comparison"><div className="kl-typical"><span className="kl-eyebrow">Typical app</span><div>Math <strong>82%</strong></div><div>Reading <strong>74%</strong></div><p className="kl-small">A score tells part of the story.</p></div><div className="kl-better"><span className="kl-eyebrow">KinderLearner</span><p><Check size={17} aria-hidden="true"/> Counting to 10</p><p><Check size={17} aria-hidden="true"/> Number recognition</p><div><span>Learning</span><strong>Breaking 7 into smaller groups</strong></div><div><span>Up next</span><strong>Early addition</strong></div></div><p className="kl-sample">Illustrative comparison</p></div></div><LearningLoop/></Section>
  <Section eyebrow="A whole-child view" title="Five ways children grow" tone="white"><p className="kl-intro">Reading and math are only part of the picture. There’s room for memory, imagination, problem solving and understanding one another.</p><div className="kl-power-grid">{powers.map(power=><LearningPowerCard key={power.name} power={power}/>)}</div></Section>
  <Section eyebrow="The right next step" title="It adapts to what your child actually knows"><div className="kl-copy-columns"><p>Two children the same age don’t necessarily need the same lesson. One may recognize every number but still be learning what those numbers represent.</p><p>Another may know the alphabet but still be learning how sounds combine into words. KinderLearner follows the skills beneath broad labels like “Reading” and “Math” and moves forward when your child is ready.</p></div><AdaptiveLearningFlow/></Section>
  <Section tone="sage"><div className="kl-split"><div><p className="kl-eyebrow">Understanding, not just completion</p><h2>Progress that means more than completing a level</h2><p>KinderLearner doesn’t assume a child has mastered something just because they answered a few questions correctly.</p><p>Confidence grows when children solve skills independently, practice them in different ways, handle more challenging versions and remember them later.</p></div><MasteryEvidenceCard/></div></Section>
  <Missions page="home"/><Coach page="home"/>
  <Section eyebrow="Our teaching philosophy" title="Built around how young children learn" tone="white"><div className="kl-grid kl-grid-three">{[['Intentional Teaching','Clear, age-appropriate instruction when a child needs it.'],['Guided Play','Opportunities to explore, experiment and discover instead of simply memorizing.'],['Practice','Important skills return without turning learning into endless repetition.'],['Retrieval','Skills reappear later to see whether the learning has really stuck.'],['Real-World Learning','Objects, movement, conversation and family routines become part of the learning experience.'],['Parent Participation','Simple guidance helps parents reinforce exactly what their child is learning.']].map(([title,copy],i)=><article className="kl-philosophy" key={title}><span className="kl-step-number">0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></Section>
  <Section><div className="kl-split"><div><p className="kl-eyebrow"><Timer size={16} aria-hidden="true"/> A good place to stop</p><h2>Designed for learning — not endless screen time</h2><p className="kl-lead">KinderLearner is designed around short, focused sessions.</p><p>A typical adventure mixes something familiar, something new and a little room to wonder.</p><p className="kl-statement"><strong>Then it’s time to do something else.</strong></p></div><div className="kl-session-card"><h3>Today’s Adventure</h3><ShortSessionTimeline/></div></div></Section><Privacy/>
  <Section title="Built for Pre-K and Kindergarten"><div className="kl-grid kl-grid-two"><AgePathCard page="prek"/><AgePathCard page="kindergarten"/></div></Section>
</>;}

function SkillGroup({title,items,domain=0}:{title:string;items:string[];domain?:number}){return <article className="kl-skill-group" style={{'--domain':powers[domain].color} as CSSProperties}><span className="kl-domain-icon"><Icon icon={powers[domain].icon}/></span><h3>{title}</h3><ul>{items.map(item=><li key={item}><Check size={15} aria-hidden="true"/>{item}</li>)}</ul></article>;}
function PreKStory(){return <>
  <Section id="how-it-works" eyebrow="Before Kindergarten" title="What should a Pre-K child be learning?"><p className="kl-intro">Think foundations, not a race. These are skills to explore through play, conversation and everyday routines, at your child’s pace.</p><div className="kl-grid kl-grid-two"><SkillGroup title="Early Reading & Language" items={['Rhyming','Beginning sounds','Letter recognition','Letter sounds','Vocabulary','Listening','Storytelling','Early sound blending']}/><SkillGroup title="Early Math" domain={1} items={['Counting','Matching numbers to quantities','Shapes','Patterns','Comparing groups','More and less','Number order','Breaking numbers into smaller groups']}/><SkillGroup title="Memory & Thinking" domain={2} items={['Remembering sequences','Following directions','Waiting before responding','Changing rules','Sorting','Planning','Problem solving']}/><SkillGroup title="Social & Emotional Skills" domain={4} items={['Emotions','Sharing','Friendship','Classroom situations','Perspective','Kindness','Problem solving']}/></div></Section>
  <Section tone="sage"><div className="kl-split"><div><p className="kl-eyebrow">Different strengths. Different next steps.</p><h2>Not every four-year-old needs the same lesson</h2><p>A child may be advanced in numbers while still developing sound awareness. Another might have a strong vocabulary but need more practice following multi-step directions.</p><p>KinderLearner builds an evolving picture of what your child understands and uses it to select useful activities.</p></div><MasteryEvidenceCard/></div></Section><Missions page="prek"/><Coach page="prek"/>
  <Section title="Designed around play, not worksheets" tone="white"><div className="kl-copy-columns"><p>KinderLearner combines guided play, short instruction, puzzles, movement, matching, sorting, drawing, tracing, stories, memory challenges and parent-child activities.</p><p className="kl-statement">Learning should feel like discovering something —<br/><strong>not completing a worksheet.</strong></p></div></Section>
</>;}
function KindergartenStory(){return <>
  <Section id="how-it-works" eyebrow="Practice with a purpose" title="Built around what your child actually knows"><p className="kl-intro">Two Kindergarten students can sit in the same classroom and need completely different practice at home.</p><div className="kl-grid kl-grid-three">{[['Reading with confidence','One may read simple words but struggle with number sense.'],['Connecting sounds','Another may understand addition but still be developing sound blending.'],['Remembering the steps','Another may know the answers but struggle to hold several instructions in memory.']].map(([title,body],i)=><article className="kl-philosophy" key={title}><span className="kl-step-number">0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div><p className="kl-section-close">KinderLearner adapts around those differences.</p></Section>
  <Section tone="white"><div className="kl-grid kl-grid-two"><div><h2>Kindergarten Reading Practice</h2><SkillGroup title="From sounds to words" items={['Letter recognition','Beginning sounds','Phoneme awareness','Letter-sound relationships','Blending sounds','Decoding simple words','Vocabulary','Listening comprehension']}/><p>KinderLearner doesn’t assume that knowing the alphabet means a child is ready to read. Each skill builds on the one before it.</p></div><div><h2>Kindergarten Math Practice</h2><SkillGroup domain={1} title="From objects to ideas" items={['Counting','Quantities','Number recognition','Number order','Comparing quantities','Composing numbers','Decomposing numbers','Early addition','Early subtraction','Patterns','Shapes','Spatial reasoning']}/><p>Whenever possible, KinderLearner first makes the idea visible — then gradually introduces numbers and symbols.</p></div></div></Section>
  <Section eyebrow="Brain Power" title="Build the mental skills behind learning"><p className="kl-intro">Success in Kindergarten requires more than academic knowledge.</p><div className="kl-copy-columns"><p>Children also need to remember instructions, ignore distractions, wait before responding, switch between rules, recognize patterns and sequence information.</p><p>KinderLearner’s Brain Power activities practice these skills through playful memory, attention and flexible-thinking challenges.</p></div></Section>
  <Section tone="sage"><div className="kl-split"><div><p className="kl-eyebrow">Learning that lasts beyond today</p><h2>Practice doesn’t mean repeating the same thing forever</h2><p>KinderLearner remembers what your child has practiced. A skill may first appear using physical objects, later using pictures, and later still as a number problem. After some time has passed, KinderLearner may bring it back again.</p><p className="kl-statement">Not just “I remember this screen.”<br/><strong>“I understand this idea.”</strong></p></div><MasteryEvidenceCard/></div></Section>
  <Section eyebrow="Support without pressure" title="Help when your child actually needs it"><p className="kl-intro">A wrong answer isn’t the end of an activity. It’s information about what kind of help may be useful next. The goal is to teach — not just test.</p><AdaptiveLearningFlow steps={['Try again','Get a hint','See it visually','Practice an easier version','Return to the original challenge']}/></Section><Missions page="kindergarten"/><Coach page="kindergarten"/>
</>;}

/** Pure shared markup keeps the entire marketing experience identical before and after hydration. */
export function KinderLearnerContent({page}:{page:KinderLearnerPage}){const meta=KINDERLEARNER_PAGES[page];return <div className="kl-site">
  <a className="kl-skip" href="#kl-main">Skip to content</a>
  <div className="kl-launch-banner"><span>{KINDERLEARNER.availability}</span><a href="/kinderlearner/support">Questions? Get in touch <ArrowRight size={15} aria-hidden="true"/></a></div>
  <header className="kl-header"><div className="kl-container"><Brand/><nav aria-label="KinderLearner navigation"><a href="/kinderlearner" aria-current={page==='home'?'page':undefined}>Overview</a><a href={KINDERLEARNER_PAGES.prek.path} aria-current={page==='prek'?'page':undefined}>Pre-K</a><a href={KINDERLEARNER_PAGES.kindergarten.path} aria-current={page==='kindergarten'?'page':undefined}>Kindergarten</a></nav><a className="kl-back" href="/">Explore schools <ArrowUpRight size={15} aria-hidden="true"/></a></div></header>
  <main id="kl-main"><nav aria-label="Breadcrumb" className="kl-container kl-breadcrumb"><a href="/">NYC School Ratings</a><span aria-hidden="true">/</span>{page==='home'?<span aria-current="page">KinderLearner</span>:<><a href="/kinderlearner">KinderLearner</a><span aria-hidden="true">/</span><span aria-current="page">{meta.label}</span></>}</nav><KinderLearnerHero page={page}/>{page==='home'?<HomeStory/>:page==='prek'?<PreKStory/>:<KindergartenStory/>}
  {page!=='home'&&<Section title="Find your child’s next chapter"><div className="kl-grid kl-grid-two"><AgePathCard page={page==='prek'?'kindergarten':'prek'}/><a className="kl-age-card" href="/kinderlearner"><span className="kl-eyebrow">The whole picture</span><h3>Meet KinderLearner</h3><p>Discover all five learning powers, our privacy-first philosophy and a thoughtful approach to short sessions.</p><span className="kl-text-link">How it all fits together <ArrowRight size={18} aria-hidden="true"/></span></a></div></Section>}
  <KinderLearnerFAQ page={page}/><Section title="A little help with the bigger picture" className="kl-resources"><p>NYC Schools Ratings helps parents understand schools. KinderLearner helps parents understand how their child is learning.</p><div className="kl-resource-links"><a href="/program/prek">Explore NYC Pre-K schools <ArrowRight size={16} aria-hidden="true"/></a><a href="/blog/best-nyc-kindergartens-2026">NYC Kindergarten school guide <ArrowRight size={16} aria-hidden="true"/></a><a href="/blog/nyc-prek-3k-kindergarten-admissions-demand-2025">Understand early-years admissions <ArrowRight size={16} aria-hidden="true"/></a></div></Section><Closing page={page}/>
  {kinderLearnerStartHref()==='#start-kinderlearner'&&<Section id="start-kinderlearner" className="kl-availability" title="Coming soon to iPhone and iPad"><p>KinderLearner for iOS and iPadOS is on its way. No public App Store download link or release date has been announced. The pages above preview the broader learning vision; phonics, sound blending and additional executive-function games are planned, not features of the current build.</p><a className="kl-button" href="/kinderlearner/support">Ask about KinderLearner <ArrowUpRight size={18} aria-hidden="true"/></a></Section>}
  </main><footer className="kl-footer"><div className="kl-container"><Brand/><p>Small discoveries. Meaningful growth.</p><nav aria-label="Footer"><a href="/">School search</a><a href="/family">Family calendar</a><a href="/kinderlearner/privacy">Privacy</a><a href="/kinderlearner/terms">Terms</a><a href="/kinderlearner/support">Support</a><a href="/kinderlearner/delete-data">Data &amp; deletion</a></nav><span className="kl-small">© 2026 NYC School Ratings</span></div></footer>
</div>;}
