/** Editorial interpretation of the reproducible 2026 summary-sheet analysis. */
export const surveyStories:Record<string,{eyebrow:string;headline:string;takeaway:string;intro:string;sections:{title:string;text:string;evidence?:string}[];questions:{q:string;a:string}[]}> = {
  'nyc-school-survey-2026': {
    eyebrow:'The big picture',headline:'Five perspectives. Not one school score.',
    takeaway:'The useful question is not “Which school wins the survey?” It is “What does each group experience—and whose feedback can we actually see?”',
    intro:'A school can look reassuring in a family survey while students describe a more complicated everyday experience. That is not automatically a contradiction. Families, teachers and students answer different questions, and early-childhood centers use their own instruments. We examined all five official 2026 summary files to separate the signals parents can use from the comparisons they should avoid.',
    sections:[
      {title:'First, separate participation from visibility',text:'The official citywide report counts 871,154 respondents across families, students and teachers, excluding Birth-to-Five and support staff. Our five summary files contain 7,039 source records. Those are school- or center-level observations, not 7,039 people or distinct schools. The same provider can appear in more than one file. Even a record that exists may contain no published scores, so file size alone overstates how much feedback a parent can read.',evidence:'coverage'},
      {title:'Family feedback is positive—but that makes small differences less useful',text:'In the K–12 family file, the median satisfaction-with-education score is 94 among 1,792 reporting records. Parent-teacher trust has a median of 97. When scores cluster near the ceiling, a one- or two-point gap is a poor reason to remove a school from a shortlist. Look instead for a pattern across communication, involvement and facilities, then check how many people responded. These are medians of published school records, not the share of all NYC parents who are satisfied.',evidence:'family-overview'},
      {title:'Teacher feedback adds a different set of questions',text:'Teacher results are more uneven across topics. Instructional leadership has a median published score of 92; teacher influence has a median of 68. Those measures are not interchangeable, and a 24-point separation is not a causal explanation. It is a reason to ask how staff participate in decisions, how collaboration works and how leadership responds to classroom needs. A single teacher composite would erase this distinction.'},
      {title:'Student voice starts a new baseline',text:'The student instrument changed substantially for 2026. Treat this release as a starting point, not proof of improvement or decline since last year. Among 1,062 reporting records, the median Safety topic score is 82, while Personal Attention and Support is 61. Feeling physically safe and feeling individually supported are different experiences. Both deserve a place in a school visit.'},
      {title:'Birth-to-5 is included—and its gaps matter',text:'Both Birth-to-5 files are included. The family file has 1,040 records with at least one published score out of 1,243. The teacher file has only 151 out of 1,057. That does not establish that the other centers are poor quality, or that their teachers are dissatisfied. It means the public summary does not provide a usable score for those records. A trustworthy profile needs to say that clearly rather than show zero or an alarming red grade.'},
      {title:'Use the findings to build a better shortlist',text:'Start with the programs, location and practical needs that matter to your family. Open a school profile and read the survey section one respondent group at a time. Choose one encouraging signal and one question to explore. A high score is an opening for a conversation—not a guarantee about your child’s experience. The survey layer complements academic data and neighborhood safety; it does not replace either.'},
    ],questions:[{q:'Did you add both Birth-to-5 datasets?',a:'Yes. Family and teacher results are stored separately and shown on exactly matched center and canonical school profiles. They are center-wide results, not specifically a 2-K cohort.'},{q:'Can I compare the family and student numbers directly?',a:'Not as equivalent measures. Questions, respondent groups and scoring context differ. Use each perspective to identify questions, not to subtract one group’s score from another.'}],
  },
  'nyc-family-survey-2026': {
    eyebrow:'Family experience',headline:'Parents report high satisfaction. The detail is where the story lives.',
    takeaway:'With satisfaction scores clustered near the top, participation and the pattern across topics matter more than tiny differences between schools.',
    intro:'For a parent choosing a school, “families are happy here” sounds like the answer. The 2026 family file offers something more useful: separate views of education, trust, communication, involvement and facilities. We examined 1,846 summary records, including 1,792 with published scores, to see what the numbers reveal—and where they stop being a helpful ranking tool.',
    sections:[
      {title:'Trust is near the ceiling; the experience is not one-dimensional',text:'Parent-teacher trust and inclusive leadership each have a median published score of 97. Satisfaction with education is 94, parent involvement is 92 and facilities and services is 91. These are different topics rather than interchangeable tests of quality. The pattern suggests that a broad positive impression can coexist with more specific questions about participation or practical services. Each median gives equal weight to a reporting record; it is not a citywide respondent percentage.',evidence:'family-topics'},
      {title:'Why a score of 94 does not separate a school from the pack',text:'Of the 1,792 records reporting satisfaction with education, 1,622 score at least 90. That concentration makes it hard to distinguish schools using this number alone. A school’s 96 should not automatically beat another school’s 94 in your decision. The public summary does not supply the uncertainty needed to call that difference statistically meaningful. Program fit, a visit and the participation context can be more useful than the last digit.',evidence:'family-distribution'},
      {title:'More families responded in four boroughs',text:'The official citywide report provides a separate participation comparison: Queens rose from 48% in 2025 to 52% in 2026, the largest gain among the five boroughs. Manhattan rose three percentage points, Brooklyn two and the Bronx one. Staten Island fell two. These figures cover geographic districts and exclude District 75 and charters. They measure response rates, not rising satisfaction; more responses do not necessarily mean happier families.',evidence:'borough'},
      {title:'Do not let a broad topic hide a specific need',text:'IEP service satisfaction appears in fewer records than the broad family topics. Advocacy and other age-specific measures have still narrower coverage. An absent result may reflect the population or reporting rules, not a failure of the school. If your child needs a particular service, ask about that service directly. A high overall impression from other families is not evidence that every child’s support needs are met.'},
      {title:'A practical school-visit checklist',text:'Ask how teachers communicate progress between report cards, what happens when a parent raises a concern, and how the school makes involvement possible for working families. For a lower facilities score, ask what respondents were referring to instead of guessing from the label. Bring the reporting year and topic with you. The goal is to turn feedback into a specific, answerable question rather than an accusation.'},
    ],questions:[{q:'Is a 94 topic score the same as 94% of all parents?',a:'No. The displayed number is a published topic score based on survey responses. The article median is a summary across reporting school records, not a weighted citywide parent percentage.'},{q:'Does a higher response rate remove bias?',a:'No. It shows broader participation, but people who respond may still differ from those who do not. Response counts are not necessarily the number answering each individual question.'}],
  },
  'nyc-teacher-survey-2026': {
    eyebrow:'Inside the staff room',headline:'Leadership scores are high. Teacher voice tells a more complicated story.',
    takeaway:'Read teaching conditions topic by topic. A strong leadership score should not hide questions about classroom behavior, discussion or staff influence.',
    intro:'Parents rarely see the daily work behind a classroom: how teachers collaborate, how decisions are made and what gets in the way of instruction. The 2026 teacher survey puts some of that experience into view. Of 1,770 summary records, 1,763 contain at least one published topic score. The main finding is not a single verdict on NYC schools—it is how much the pattern changes across topics.',
    sections:[
      {title:'The topic pattern is more revealing than a composite',text:'Instructional leadership has a median score of 92 and peer collaboration 90. Teacher influence and classroom behavior each have medians of 68; preventing bullying is 67. Different questions underpin these measures, so these gaps are descriptive, not a controlled comparison. Still, they make the case for showing separate dimensions rather than averaging everything into an upbeat headline.',evidence:'teacher-topics'},
      {title:'Teacher influence varies across schools',text:'The distribution below shows the range of published Teacher Influence scores, not a ranking of principals or an estimate of teacher retention. A low score can be a prompt to ask how staff contribute to decisions. It cannot tell us from this dataset alone whether a particular policy caused dissatisfaction, whether teachers will leave or whether academic outcomes will change.',evidence:'teacher-distribution'},
      {title:'High outreach does not answer every communication question',text:'Outreach to Parents has a median published teacher score of 98. That is encouraging as a description of responding staff, but it is not proof that every family receives information in the form they need. Use the family survey alongside it as a separate perspective. If the two accounts feel different, ask about translation, communication channels and how concerns are followed up. Do not calculate an average across the two instruments.'},
      {title:'Coverage is part of the interpretation',text:'Some topics apply to a narrower set of schools. Early Childhood Instruction appears in 423 records and Safety in 941, while several broader topics appear in about 1,762. A median based on a narrower group is not directly comparable to an all-school measure. The tables show the reporting count for each topic so that a tidy bar chart does not imply identical populations.'},
      {title:'What to ask—and what not to infer',text:'Ask how new teachers are supported, how staff plan together and how teachers influence school decisions. Ask for a concrete example of a change made after staff feedback. Do not use this survey as evidence of staffing stability, individual teacher quality or a causal effect on test scores. Those questions require different data. For your shortlist, the survey is most useful as a window into the working environment behind instruction.'},
    ],questions:[{q:'Does a lower teacher score mean a school is unsafe?',a:'No. Safety, preventing bullying, classroom behavior and teacher influence are separate topics. Their wording and reporting populations differ. Read the relevant topic and ask the school for context.'},{q:'Are these year-over-year teacher trends?',a:'No. This analysis describes the 2026 file. We do not show school-level changes until prior-year questions and scoring are checked for comparability.'}],
  },
  'nyc-student-survey-2026': {
    eyebrow:'Student voice',headline:'Feeling safe and feeling supported are different experiences.',
    takeaway:'The 2026 student results open a new baseline. Use them to ask about daily experience, not to claim a school improved or declined since 2025.',
    intro:'A parent can learn a lot by asking where a child feels comfortable—and whether an adult notices when they need help. The redesigned 2026 student survey offers separate measures for safety, relationships and support. We examined 1,123 summary records, of which 1,062 report topic scores. The evidence suggests a richer conversation than simply asking whether students like their school.',
    sections:[
      {title:'Support deserves as much attention as safety',text:'Across reporting records, the median Safety topic score is 82. Student-Teacher Trust is 73 and Personal Attention and Support is 61. Those numbers do not measure the same thing, and we should not treat their difference as an estimate of unmet need. They show why a family should ask about relationships and individual attention even when a school’s safety feedback is reassuring.',evidence:'student-topics'},
      {title:'The setting matters inside a school',text:'The official citywide report offers a more specific lens: 92% favorable responses for feeling safe in classrooms, 87% in hallways and cafeterias, and 84% in locker rooms and bathrooms. These are individual-question results, not the summary Safety topic and not our school-record medians. The eight-point classroom-to-locker-room/bathroom difference points to a practical conversation about supervision and reporting concerns in different spaces.',evidence:'student-settings'},
      {title:'One median cannot describe every school',text:'The distribution of Personal Attention and Support scores shows why a citywide headline is not enough. Your child will attend a particular school, not the median school in the file. Read the matched profile and ask how students find a trusted adult, how concerns are followed up and how the school recognizes a student who is quietly struggling.',evidence:'student-distribution'},
      {title:'A new questionnaire means a new starting line',text:'Changes to the 2026 instrument break a simple comparison with earlier student survey scores. A lower number than last year could reflect changed questions or scoring rather than a worse experience. This article deliberately contains no prior-year student line chart, red decline badge or improvement claim. Future comparisons must start with questions and populations that are genuinely comparable.'},
      {title:'Keep the neighborhood out of the classroom measure',text:'The neighborhood safety index describes police complaints around a location. Student survey feedback describes experience inside school. Neither can stand in for the other. A concern about the commute calls for one set of questions; a concern about bullying, bathrooms or adult support calls for another. Seeing both measures on a profile should help parents separate those decisions, not blend them into one fear or reassurance.'},
    ],questions:[{q:'Why is there no 2025 comparison?',a:'The student instrument changed substantially for 2026. A direct year-over-year comparison could mistake a measurement change for a change in school experience.'},{q:'Why do the citywide safety questions differ from the profile score?',a:'The citywide figures are individual-question favorable-response percentages. Profiles show published topic summaries, which combine question information. They are different measures.'}],
  },
  'nyc-early-childhood-survey-2026': {
    eyebrow:'Birth-to-5 · Two separate datasets',headline:'Families sound positive. Teacher feedback is much harder to see.',
    takeaway:'Both Birth-to-5 datasets are here. Strong family scores need participation context; missing teacher scores must never become a negative judgment about a center.',
    intro:'For families looking at 2-K, 3-K or pre-K, test-score rankings are the wrong tool. Relationships, communication and the everyday learning environment are more relevant questions. The Birth-to-5 family and teacher surveys provide two distinct views. We analyzed 1,243 family-file records and 1,057 teacher-file records. The most important finding is as much about what is not published as what is.',
    sections:[
      {title:'Family feedback: positive scores with a ceiling effect',text:'Among the 1,037 records reporting Family Satisfaction with Child’s Education, the median score is 100. Parent-Teacher Trust also has a median of 100 among 1,039 reporting records; Outreach to Parents is 98. That is positive feedback from respondents, but it leaves little room for a simple ranking to discriminate among centers. A perfect published score is not a guarantee about every family’s experience.',evidence:'b5-family'},
      {title:'The family file needs a participation lens',text:'There are 432 family-file records with fewer than ten responses. The Birth-to-5 summary does not supply response rates, so we cannot tell parents what share of eligible families those counts represent. We show the count, keep the rate as “Not reported” and flag small counts. Our under-ten caution is a product convention, not a claim about the official suppression threshold. Missing values can have more than one explanation.',evidence:'b5-family-distribution'},
      {title:'Teacher feedback: included does not mean fully visible',text:'The teacher dataset is imported in full, but only 151 of its 1,057 records contain any published topic score. The other 906 contain none. There are 992 records with fewer than ten teacher responses. These counts do not prove why a particular score is missing. Small staff teams and reporting rules are important context, but the file itself should not be used to diagnose the reason for every blank.',evidence:'b5-coverage'},
      {title:'What the published teacher subset can tell us',text:'Within the much smaller reporting subset, Early Childhood Instruction and Peer Collaboration have median scores of 100. Classroom Behavior is 76 and Teacher Influence is 82.5. These describe reporting records only—not all NYC early-childhood teachers or centers. Guidance, Safety and Strong Core Instruction have no published topic scores anywhere in this teacher summary, so we do not draw a bar or infer a result for those topics.',evidence:'b5-teacher'},
      {title:'A center-wide result is not a 2-K result',text:'A provider may offer 2-K, 3-K and pre-K under one canonical school record. Birth-to-5 feedback belongs to the center, not automatically to one age group or classroom. We match by official center identifiers and existing school relationships. A shared address or a similar name is not enough. The survey also does not establish current seats, admissions priority or automatic progression into kindergarten.'},
      {title:'Use the data when you visit',text:'Ask how staff describe a child’s day, how caregivers communicate concerns and how teachers adapt activities for different developmental stages. If the teacher panel has no published scores, ask about staff support and continuity directly rather than assuming a problem. For a high family score, ask what families value most. The most useful result is a more focused conversation about the center your child would actually attend.'},
    ],questions:[{q:'Are the family and teacher datasets both on profiles?',a:'Yes, wherever their official identifiers match. They have separate cards, sources and response counts. A teacher record with no published scores is shown as a coverage limitation, not omitted or scored zero.'},{q:'Can I use this to rank 2-K providers?',a:'Not as an academic or 2-K-specific ranking. The feedback is center-wide, coverage varies and many family scores cluster at the ceiling. Use it alongside program fit and a visit.'}],
  },
};
