import React from 'react';
import { RelatedBlogReading } from './RelatedBlogReading';
import { SURVEY_INSIGHTS, type SurveyInsight } from './survey-insights';
import { SURVEY_SOURCE, SURVEY_GUIDE } from './surveys';
import { surveyStories } from './survey-stories';
import { SurveyArticleEvidence } from './SurveyArticleEvidence';
import { CoverageEvidence } from './SurveyCharts';
import { instrumentNames, surveyAnalysis } from './survey-analysis';

export function SurveyInsightContent({page}: {page: SurveyInsight}) {
  const story=surveyStories[page.slug],sections=story?.sections??page.sections;
  return <article className="survey-article text-foreground">
    <nav aria-label="Breadcrumb" className="text-sm text-muted-foreground mb-8 flex flex-wrap gap-2"><a className="underline" href="/">Home</a><span>/</span><a className="underline" href="/blog">Blog</a><span>/</span><span aria-current="page">{page.title}</span></nav>
    <header className="border-b pb-8 mb-8"><p className="text-blue-700 dark:text-blue-300 text-sm font-semibold uppercase tracking-wider">2026 Data analysis · {story?.eyebrow??'Sources & interpretation'}</p><h1 className="text-3xl sm:text-5xl font-bold tracking-tight leading-tight mt-4 mb-5">{page.title}</h1><p className="text-lg text-muted-foreground leading-relaxed">{page.description}</p><p className="text-sm text-muted-foreground mt-5">By NYC School Ratings Team · September 15, 2026 · {story?'7':'4'} min read</p></header>
    {story&&<><div className="rounded-xl border border-blue-200 dark:border-blue-800 bg-blue-50 dark:bg-blue-950/40 p-5 sm:p-7 mb-8"><p className="text-xs font-bold uppercase tracking-wide text-blue-700 dark:text-blue-300 mb-3">The takeaway</p><h2 className="text-2xl font-bold mb-3">{story.headline}</h2><p className="leading-relaxed">{story.takeaway}</p></div><p className="text-lg leading-8 mb-8">{story.intro}</p></>}
    <nav aria-label="In this analysis" className="rounded-xl border p-5 mb-10"><p className="font-semibold mb-3">In this analysis</p><ol className="list-decimal pl-5 space-y-2 text-sm">{sections.map((s,i)=><li key={s.title}><a className="underline underline-offset-4 hover:text-blue-600" href={`#finding-${i+1}`}>{s.title}</a></li>)}</ol></nav>
    {sections.map((section,i)=><section className="my-10 scroll-mt-8" key={section.title} id={`finding-${i+1}`}><h2 className="text-2xl font-bold tracking-tight mb-4">{section.title}</h2><p className="text-base sm:text-lg leading-8 text-muted-foreground">{section.text}</p><SurveyArticleEvidence id={'evidence' in section?section.evidence as string:undefined}/></section>)}
    {page.slug==='survey-methodology'&&<><CoverageEvidence/><section className="my-10"><h2 className="text-2xl font-bold mb-4">How the article charts are calculated</h2><p className="leading-8 text-muted-foreground">Each topic median gives one equal vote to each source record with a published value. It is not weighted by response count and must not be described as the percentage of all NYC respondents. Blank and N/A values are excluded topic by topic. We include unmatched source records in the article analysis so directory coverage does not select the analytical sample. Profile display still requires an exact identifier match.</p><p className="leading-8 text-muted-foreground mt-4">The middle-half range is the 25th to 75th percentile using linear interpolation (R-7). It describes variation across records, not statistical uncertainty. Score bands are descriptive positions on a 0–100 scale, not official quality grades. No causal claims or prior-year student comparisons are calculated.</p></section></>}
    {page.slug==='nys-test-results-2026'&&<div className="overflow-x-auto border rounded-xl my-8"><table className="w-full text-left text-sm"><caption className="p-4 text-left font-bold">Assessment release versus survey release</caption><thead className="bg-muted"><tr><th className="p-3">Data</th><th className="p-3">Current use</th><th className="p-3">Next step</th></tr></thead><tbody><tr className="border-t"><th className="p-3">2026 preliminary assessments</th><td className="p-3">Not imported into school ratings</td><td className="p-3">Verify final public school-level files</td></tr><tr className="border-t"><th className="p-3">2026 surveys</th><td className="p-3">Five separate feedback datasets</td><td className="p-3">Read profiles and instrument-specific findings</td></tr><tr className="border-t"><th className="p-3">Existing assessments</th><td className="p-3">Keep their displayed reporting year</td><td className="p-3">Preserve historical results</td></tr></tbody></table><p className="p-4 text-muted-foreground">No 2026 school-level assessment chart is shown because those public school-level results have not been imported. Survey feedback cannot fill that gap.</p></div>}
    {story&&<section className="my-10"><h2 className="text-2xl font-bold mb-4">Questions parents ask</h2>{story.questions.map(({q,a})=><details key={q} className="border-b py-3"><summary className="font-medium cursor-pointer py-2">{q}</summary><p className="leading-7 text-muted-foreground pb-3">{a}</p></details>)}</section>}
    <aside className="bg-muted rounded-xl p-6 my-10"><h2 className="text-xl font-bold mb-3">Bring the findings back to your child’s shortlist</h2><p className="leading-7 mb-4">Open a profile and look for “What the school community says.” Read the respondent group, year and participation before interpreting a score.</p><div className="flex flex-wrap gap-3"><a className="inline-flex min-h-11 items-center rounded-lg bg-blue-600 text-white px-4 font-medium" href="/">Find a school →</a><a className="inline-flex min-h-11 items-center rounded-lg border bg-background px-4 font-medium" href="/early-childhood">Explore early childhood →</a></div></aside>
    <section className="border-t pt-8 my-8"><h2 className="text-2xl font-bold mb-4">Sources, scope and limitations</h2><p className="text-sm text-muted-foreground leading-7 mb-4">Analysis snapshot: September 15, 2026. School/center medians are our analysis of the official summary sheets; individual-question citywide percentages and borough participation rates are attributed separately to NYCPS. Topic coverage varies. Published scores reflect respondents and do not establish cause, admissions availability or academic quality.</p><ul className="space-y-2 text-sm"><li><a className="underline" href={page.source} target="_blank" rel="nofollow noopener noreferrer">Official source for this page ↗</a></li><li><a className="underline" href={SURVEY_SOURCE} target="_blank" rel="nofollow noopener noreferrer">NYC School Survey data downloads ↗</a></li><li><a className="underline" href={SURVEY_GUIDE} target="_blank" rel="nofollow noopener noreferrer">2026 scoring technical guide ↗</a></li><li><a className="underline" href="/blog/survey-methodology">Our methodology and matching rules</a></li></ul><details className="mt-5 text-sm"><summary className="cursor-pointer py-3 font-medium">Audit the five source files</summary><ul className="space-y-3">{surveyAnalysis.releases.map(r=><li key={r.instrument}><a className="underline" target="_blank" rel="nofollow noopener noreferrer" href={r.sourceUrl}>{instrumentNames[r.instrument as keyof typeof instrumentNames]} ↗</a><p className="text-xs break-all text-muted-foreground">SHA-256: {r.sourceHash}</p></li>)}</ul></details></section>
    <section className="border-t pt-8"><h2 className="text-2xl font-bold mb-5">Continue the analysis</h2><div className="grid sm:grid-cols-2 gap-4">{SURVEY_INSIGHTS.filter(p=>p.slug!==page.slug).map(p=><a className="border rounded-xl p-5 hover:border-blue-500 block" key={p.slug} href={`/blog/${p.slug}`}><h3 className="font-semibold mb-2">{p.title} →</h3><p className="text-sm text-muted-foreground">{p.description}</p></a>)}</div></section>
    <RelatedBlogReading slug={page.slug} />
    <p className="leading-7 my-6">See the data on a profile: {page.slug==='nyc-early-childhood-survey-2026' ? <a className="underline" href="/school/18kavq-hebrew-educational-society-of-brooklyn-18kavq#school-community-survey">Hebrew Educational Society of Brooklyn’s Birth-to-5 feedback</a> : <a className="underline" href="/school/01m015-ps-015-roberto-clemente#school-community-survey">P.S. 015 Roberto Clemente’s community feedback</a>}. Check the respondent group and participation; these are examples, not endorsements or representative citywide samples.</p>
    <p className="text-xs text-muted-foreground mt-8">Independent analysis of public NYCPS data. <a className="underline" href="/contact">Report a correction</a>.</p>
  </article>;
}
