import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { calculateAcademicScore, calculateOverallScore, type School } from "../shared/schema";
import { normalizeSchool, filterPrograms, schoolBorough } from "../shared/early-childhood";
import { getSchoolSeoMeta } from "../shared/school-seo";
import { measurement, planTwok, validateSnapshot, repairEncoding, fetchTwok, type Snapshot } from "../server/twokImport";

const record = (dbn: string) => ({ school: { dbn, name: "José’s Daycare", school_year: "2025-26 School Year", district: { code: "06", borough: "Manhattan" }, address: { address_1: "123 Shared Street", latitude: "40.8", longitude: "-73.9" } }, admission_process: "2K", programs: [{ name: "2-K - School Day", program: { admission_process: "2-K" } }], other_features: [{ name: "Offers 3-K" }, { name: "Offers pre-K" }], total_enrollment: "" });
const snapshot: Snapshot = { processId: 48, cycle: "2025-26 School Year", verifiedAt: "2026-09-13T00:00:00Z", count: 2, records: [record("06G123"), record("06H123")] };
const k12 = { dbn: "06G123", name: "Existing URL Name", district: 6, address: "Preserve", grade_band: "PK-5", has_2k: false, has_3k: true, has_prek: false, ela_proficiency: 80, math_proficiency: 80, climate_score: 80, progress_score: 80, academics_score: 80, enrollment: 0, student_teacher_ratio: 0 } as School;
assert.equal(measurement(""), null);
assert.equal(measurement(-1), null);
assert.equal(measurement("0"), 0);
assert.equal(normalizeSchool(k12).enrollment, 0);
const legacy = { ...k12, grade_band: "2K", academics_score: -1, climate_score: -1, progress_score: -1 };
assert.equal(normalizeSchool(legacy).enrollment, null);
assert.equal(normalizeSchool({ ...legacy, enrollment: 12 }).enrollment, 12);
assert.equal(calculateOverallScore(k12), 80);
assert.equal(calculateOverallScore({ ...k12, climate_score: null }), -1);
assert.equal(calculateOverallScore({ ...k12, grade_band: "2K" }), -1);
assert.equal(calculateAcademicScore({ ...k12, grade_band: "2K" }), null);
for (const letter of ["F", "G", "H"]) assert.equal(schoolBorough({ dbn: `10${letter}123`, borough: "Queens" }), "Queens");
const plan = planTwok(snapshot, [k12], [{ semsCode: "06G123", locCode: "G123" }]);
const registrationSnapshot = { ...snapshot, records: snapshot.records.map(r => ({ ...r, name: "Provider - Register at 639 Edgecombe Avenue, Manhattan" })) };
const registrationPlan = planTwok(registrationSnapshot, []);
assert.equal(registrationPlan[0].after.address, "123 Shared Street");
assert.equal(registrationPlan[0].after.early_childhood_source.registrationInstructions, "Register at 639 Edgecombe Avenue, Manhattan");
assert.equal(plan.length, 2);
assert.equal(plan[0].after.has_2k, true);
assert.equal(plan[0].after.has_3k, true);
assert.equal(plan[0].after.has_prek, true);
assert.equal(plan[0].after.early_childhood_source.legacyCenterCode, "G123");
assert.equal(plan[0].after.grade_band, undefined);
assert.equal(plan[0].after.name, undefined);
const applied = plan.map(c => ({ ...(c.before ? k12 : {}), ...c.after, dbn: c.dbn }));
assert.equal(applied.length, 2, "same-address providers remain separate");
for (const flag of ["has_2k", "has_3k", "has_prek"]) assert.equal(filterPrograms(applied, { [flag]: "true" }).length, 2);
assert.equal(planTwok(snapshot, applied, [{ semsCode: "06G123", locCode: "G123" }]).length, 0, "same snapshot rerun is idempotent");
assert.throws(() => validateSnapshot({ ...snapshot, count: 3 }), /Incomplete/);
assert.throws(() => validateSnapshot({ ...snapshot, records: [record("06G123"), record("06G123")] }), /duplicate/);
assert.throws(() => validateSnapshot({ ...snapshot, cycle: "2026-27" }), /cycle/);
const absent = planTwok(snapshot, [{ ...k12, dbn: "06G009", has_2k: true }]).find(c => c.dbn === "06G009")!;
assert.equal(absent.action, "needs_verification");
assert.equal(absent.after.has_2k, undefined, "absence must not remove programs");
assert.equal(normalizeSchool({ ...legacy, ...absent.after }).enrollment, null, "verification status must not turn legacy defaults into measured zeros");
assert.equal(repairEncoding("José’s Daycare"), "José’s Daycare");
assert.equal(repairEncoding("JosÃ©"), "José");
assert.equal(repairEncoding("ADAÃ¢Â\u0080Â\u0099S"), "ADA’S");
const meta = getSchoolSeoMeta(normalizeSchool(legacy));
assert.match(meta.description, /not applicable/);
assert.doesNotMatch(meta.description, /0 students|\-1|proficiency/i);
const ssr = readFileSync("server/seoRenderer.ts", "utf8");
assert.match(ssr, /numberOfStudents: school.enrollment \?\? undefined/);
assert.match(ssr, /isEarlyChildhoodOnly\(school\)/);
await assert.rejects(() => fetchTwok((async () => new Response("failure", { status: 503 })) as typeof fetch), /HTTP 503/);
// Exercise actual server HTML generation against isolated storage fixtures.
const { storage } = await import("../server/storage");
const { renderSeoHtml, clearSeoCache } = await import("../server/seoRenderer");
const oldGet = storage.getSchool, oldList = storage.getSchools;
try {
  const clean = normalizeSchool({ ...legacy, ela_proficiency: null, math_proficiency: null });
  storage.getSchool = async () => clean;
  storage.getSchools = async () => [clean];
  clearSeoCache();
  const html = await renderSeoHtml("/school/06G123", '<html><head><title>Base</title></head><body><div id="root"></div></body></html>');
  assert.ok(html);
  assert.match(html, /not applicable/);
  assert.doesNotMatch(html, /0 students|"numberOfStudents":0|"ratingValue":-1|\-1\/100|guaranteed a seat/);
} finally { storage.getSchool = oldGet; storage.getSchools = oldList; clearSeoCache(); }
console.log("2-K regression checks passed: identity, programs, nulls, scoring, boroughs, encoding, pagination, metadata and idempotency.");
